config/routes.rb
Rails.application.routes.draw do
  root to: 'records#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get :followings
      get :followers
    end
    collection do
      get :search
    end
  end
  post "likes/:record_id/create", to: "likes#create", constraints: {record_id: /\d+/}, as: :likes_create
  post "likes/:record_id/delete", to: "likes#delete", constraints: {record_id: /\d+/}, as: :likes_delete
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :records, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  #counter_cahce: :like_countはリレーションされているlikeの数をリレーション先のlikes_countというカラムの値に入れる
  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {maximum: 20}
  validates :content, presence: true, length: {maximum: 255}

  has_many :likes

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 256 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password

    has_many :records
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    has_many :likes

    def follow(other_user)
      unless self == other_user
        self.relationships.find_or_create_by(follow_id: other_user.id)
      end
    end

    def unfollow(other_user)
      relationship = self.relationships.find_by(follow_id: other_user.id)
      relationship.destroy if relationship
    end

    def following?(other_user)
      self.followings.include?(other_user)
    end

    def feed_records
      Record.where(user_id: self.following_ids + [self.id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  include SessionsHelper

  def current_user
    @curernt_user = User.find_by(id: session[:user_id])
  end

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def counts(user)
    @count_records = user.records.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.new(user_id: @current_user.id, record_id: params[:record_id])
    @like.save
    @record = Record.find_by(id: @like.record_id)
    @like_count = Like.where(record_id: params[:record_id]).count
  end

  def delete
    @like = Like.find_by(user_id: @current_user.id, record_id: params[:record_id])
    #@record = Record.find_by(id: @like.record_id)
    @like.destroy
    @like_count = Like.where(record_id: params[:record_id]).count
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  #before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    if logged_in?
      @record = current_user.records.build  #form_with用
      @records = current_user.feed_records.order(id: :desc).page(params[:page])
    end
  end

  def show
    if current_user == @record.user
      set_record
    else
      redirect_to root_url
    end
  end

  def new
    @record = Record.new
  end

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      flash[:success] = '日記が正常に投稿されました'
      redirect_to root_url
    else
      @records = current_user.records.order(id: :desc).page(params[:page])
      flash.now[:danger] = '日記が正常に投稿されませんでした'
      render 'records/index'
    end
  end

  def edit
    set_record
  end

  def update
    set_record
    if @record.update(record_params)
      flash[:success] = '日記は更新されました'
      redirect_to @record
    else
      flash.now[:danger] = '日記は更新されませんでした'
      render :edit
    end
  end

  def destroy
    set_record
    @record.destroy
    flash[:success] = '日記は削除されました'
    redirect_to root_url
  end

  private

  def set_record
    @record =  Record.find(params[:id])
  end

#Strong Parameter(セキュリティパラメータ)送信されたデータをフィルタリング
  def record_params
    params.require(:record).permit(:title, :content)
  end

  def correct_user
    @record = current_user.records.find_by(id: params[:id])
    unless @records
      redirect_to root_url
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find_by(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'フォローしました'
    redirect_to user
  end

  def destroy
    user = User.find(parmas[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'フォローを解除しました'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #二段階でデータ取得, emailを小文字化で取得
    email = params[:session][:email].downcase
    #二段階でデータ取得
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private
#login(email, password)をprivateで定義
  def login(email, password)
    @user = User.find_by(email: email)
    #email, passwordの組み合わせでログインの有無が可能
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]

  def index
    #@users = User.order(id: :desc).page(params[:page].per(25))
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @records = @user.records.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      redirect_to root_url
    else
      flash.now
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'ユーザ変更がされました'
    else
      flash.now[:danger]
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'ユーザは退会されました'
    redirect_to user_url
  end

  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == @user.id
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #現在ログインしているユーザを取得
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_records.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_records.each do |record| %>
        <li><%= record %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_records.html.erb
<% flash.each do |record_type, record| %>
  <div class="alert alert-<%= record_type %>"><%= record %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-warning">
    <a class="navbar-brand" href="/">日記アプリ</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!--メニュー項目-->
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportContent">
          <ul class="navbar-nav">
            <% if logged_in? %>
              <%= link_to user_path(current_user) do %>
                <i class="fas fa-user h3"></i>
              <% end %>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-divider"></li>
                  <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                  <li class="dropdown-item"><%= link_to 'ユーザー一覧', users_path %></li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset = "utf-8">
    <meta name = "viewport" content = "width = device-width, initial-scale = 1, shrink-to-fit = no">
    <title>日記アプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
      <%= render 'layouts/flash_records' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_likes.html.erb
<% if Like.find_by(user_id: current_user.id, record_id: record.id)%>
  <%= link_to "/likes/:record_id/create", method: :delete, remote: true do %>
    <i class="material-icons">star</i>
  <% end %>
<% else %>
  <%= link_to"/likes/:record_id/delete", method: :post, remote: true do%>
    <i class="material-icons">star_border</i>
  <% end %>
<% end %>
<%= record.likes.length %>

app/views/likes/create.js.erb
$('.button_<%= @record.id %>').html("<%= j(render partial: 'likes/like')%>");

app/views/likes/delete.js.erb
$('.button_<%= @record.id %>').html("<%= j(render partial: 'likes/like')%>");

app/views/records/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: record, local: true)do |f| %>
      <div id="errors_explanation" class="alart alart-warning">
        <ul class="mb-0">
          <% record.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>

    <div class="form-group">
      <%= f.label :title, 'タイトル' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content, '内容'%>
      <%= f.text_area :content, class: 'form-control', rows: 15 %>
    </div>
      <%= f.submit '投稿', class: 'btn btn-primary ' %>
    <% end %>
  </div>
</div>

app/views/records/create.html.erb
<h1>Records#create</h1>
<p>Find me in app/views/records/create.html.erb</p>

app/views/records/destroy.html.erb
<h1>Records#destroy</h1>
<p>Find me in app/views/records/destroy.html.erb</p>

app/views/records/edit.html.erb
<h1>id: <%= @record.id %> : <%= @record.title %>の日記編集ページ</h1>

<%= form_with(model: @record, local: true ) do |f| %>
<% end %>

<h1>日記編集</h1>
<%= render 'form', record: @record %>
<%= link_to record_path do%>
  <i class="fas fa-undo-alt"></i>
<% end %>

app/views/records/index.html.erb
<% if logged_in? %>
  <h1>日記一覧</h1>
  <table class="table table-striped">
    <thead>
      <p>ユーザー名</p>
      <tr>
        <th>タイトル</th>
        <th>内容</th>
      </tr>
    </thead>
    <tbody>

      <% @records.each do |record| %>
        <tr>
          <td><%= link_to record.title, record %></td>
          <td><%= record.content %></td>
        </tr>
      <% end %>

    </tbody>
  </table>
  <%= link_to new_record_path, class: "btn btn-primary" do %>
  <i class="fas fa-pen"></i>
  <% end %>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>ようこそ日記アプリへ</h1>
      <%= link_to 'さっそく使い始める', signup_path, class: 'btn btn-primary btn-lg' %>
      <h4>登録のページへ移動します</h4>
    </div>
  </div>
<% end %>

app/views/records/new.html.erb
<h1>日記作成ページ</h1>
<%= render 'form', record: @record %>
<%= link_to root_url do%>
  <i class="fas fa-undo-alt"></i>
<% end %>

app/views/records/show.html.erb
<h1><%= @record.id %> : <%= @record.title%>の詳細ページ</h1>
<p><%= @record.content%></p>

<%= link_to root_url do%>
  <i class="fas fa-undo-alt"></i>
<% end %>
<%= link_to '編集する', edit_record_path(@record), class: 'btn btn-light' %>
<%= link_to @record, method: :delete, data: {confirm: 'ほんまに消すけどええの？'}, class: 'btn btn-danger' do %>
  <i class="far fa-trash-alt"></i>
<% end %>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <% form_with(model: current_user.relationships.find_by(follow_id: :user_id), local: true, method: :delete)do |f|%>
      <% hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー解除', class: 'btn btn-default btn-block' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, local: true)do |f| %>
      <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= render 'relationships/follow_button', user: @user%>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">日記  <span class="badge badge-secondary"><%= @count_records %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= render 'relationships/follow_button', user: @user%>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">日記  <span class="badge badge-secondary"><%= @count_records %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users%>
<% @users.each do |user| %>
  <tr>
    <td><%= link_to(user.id, user_path(user) )%></td>
    <td><%= user.name %></td>
    
    <br>
  </tr>
<% end %>

app/views/users/new.html.erb
<div class="body">
  <div class="text-center">
    <h1>新規登録</h1>
  </div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>

      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス'%>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード'%>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, '確認用パスワード'%>
        <%= f.password_field :password_confirmation, class: 'form-control'%>
      </div>
      <%= f.submit '登録する', class: 'btn btn-primary btn-block'%>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= @user.name %>
    
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">日記  <span class="badge badge-secondary"><%= @count_records %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">フォロー  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">フォロワー  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
  </div>
</div>
<%= render 'relationships/follow_button', user: @user %>